version: '2'
services:
  logspout:
    build:
      context: logspout/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Self signed cert for local nginx testing
      # - /etc/ssl/certs/localhost.crt:/opt/self/nginx.crt

      # CA cert, client cert, client key
      # - /home/damouse/.lhr/data/ca.crt:/opt/self/ca.crt
      # - /home/damouse/.lhr/data/client.crt:/opt/self/client.crt
      # - /home/damouse/.lhr/data/client.key:/opt/self/client.key

      # Testing bad keys
      # - /home/damouse/code/infra/scratch/localhost.crt:/opt/self/client.crt
      # - /home/damouse/code/infra/scratch/localhost.key:/opt/self/client.key

    environment:
      LOGSTASH_TAGS: docker-elk
      LOGSPOUT: ignore

      # Local testing without autl
      ROUTE_URIS: logstash+tcp://0.0.0.0:5000

      # TLS nginx reverse proxy auth
      # ROUTE_URIS: tls://0.0.0.0:12345
      # LOGSPOUT_TLS_CA_CERTS: /opt/self/nginx.crt
      # LOGSPOUT_TLS_CLIENT_CERT: //opt/self/client.crt
      # LOGSPOUT_TLS_CLIENT_KEY: /opt/self/client.key
      DOCKER_LABELS: 1
    network_mode: host
    restart: always
